server:
  port: 8080
  address: 0.0.0.0
spring:
  profiles:
    active: prod
#  web:
#    resources:
#      static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    map-underscore-to-camel-case: true

example:
  jwt:
    #用户端jwt
    user-secret-key: 3sB8fQ2zXc7vK9pR5tA1wS7dF4gH6jL2nZ8xC5vB7nM9kP1oU0yT
    user-ttl: 259200000
    user-token-name: authentication

